### ISSUE TITLE
Auto BG doesn't find any sectors

### ISSUE THREAD

**Issue by tigertim08** [cosmos0nash/FoE-Extender#12]
Good Morning, 

looks like the latest Update changed something in the background. Auto BG does not find any sectors
![2023-08-03_08-15-37](https://github.com/cosmos0nash/FoE-Extender/assets/24661102/8c1095e0-9e5f-4a9b-a146-35757a1e8cbd)

I checkt a couple of times and there should be a couple of sectors with 72%.

**Comment by udo27503** [comment]
Same by me. What can i do?
