### ISSUE TITLE
Liecenie bojovej jednotky

### ISSUE THREAD

**Issue by Trezorius** [cosmos0nash/FoE-Extender#13]
Ahoj, 
Je moznost aby F.E. vyliecil vzacnu jednotku a aby sa nestralila bojom.
priklad:
mesto: progresivna era
jednotka: moderna era (mam ju ako odmenu za quest)
pri automatickom boji program bojuje a nedovali ozivit takto zabitu jednotu v boji za pomoci drahokamov. (Foe helper upozorní na stratenu jednotku a odporuci ju preliecit)
Dakujem za odpoved.

**Comment by Trezorius** [comment]
![moderna arma](https://github.com/cosmos0nash/FoE-Extender/assets/145286001/1a2d94fa-d764-4fd7-a5b6-7421add2aa7a)

**Comment by cosmos0nash** [comment]
> Ahoj, Je moznost aby F.E. vyliecil vzacnu jednotku a aby sa nestralila bojom. priklad: mesto: progresivna era jednotka: moderna era (mam ju ako odmenu za quest) pri automatickom boji program bojuje a nedovali ozivit takto zabitu jednotu v boji za pomoci drahokamov. (Foe helper upozorní na stratenu jednotku a odporuci ju preliecit) Dakujem za odpoved.

Ahoj. Ste prvý a pravdepodobne jediný, kto to potrebuje. Teoreticky je to možné, ale v praxi je to dosť náročné na implementáciu a ja to neurobím, keďže pôjde o vedľajšiu a nevyužitú funkcionalitu. Odporúčam, aby ste takéto jednotky nepoužívali v automatických bitkách.

**Comment by Trezorius** [comment]
Dakujem za odpoved.
Ak mozem este otazku a funkcia ktora by bola taka že ked takato jednotka zomrie (0/10 live point) program prestane bojovat a len sa zastavi? to je tiez narocne?
Dakujem.
