### ISSUE TITLE
cursor octet_stream

### ISSUE THREAD

**Issue by NeHBzxwqL3RgFy8A** [cosmos0nash/FoE-Extender#15]
Does game anti-cheat register server request of new cursor icon to check if mouse is moving naturally?

**Comment by cosmos0nash** [comment]
> Does game anti-cheat register server request of new cursor icon to check if mouse is moving naturally?

what are you talking about?

**Comment by cosmos0nash** [comment]
> Local sometimes makes request to server for cursor icon, after it is deleted from local after certain time. These requests can be used to track whether the mouse is actually being moved: if no cursor icon request is ever made, then the cursor is not actually being moved by human, and all requests are clearly being sent by HTTP injection. Does your bot account for this?

Did you come up with that yourself? What if I have the cache disabled? What if I have cached for a long time? If you think about it that way, any request can be used to determine if the mouse has moved, because if there are no requests, then it must not have moved. only it's completely silly

**Comment by cosmos0nash** [comment]
Also use any MITM (burp, charles, etc.) and see for yourself that the browser doesn't even send preflight requests, it takes from the cache. So don't make things up, because I have never heard of a more stupid method.
