### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by adamhamilton44** [cosmos0nash/FoE-Extender#16]
many reloads and/or reinstall, confirm bot, authorize, reload browser blah blah blah every option available and nothing connecting. Yes Registered and authorized etc. Not a first time user. what is going on guys? Chromebook OS, Mozilla firefox web browser and up to date on all.

**Comment by cosmos0nash** [comment]
> many reloads and/or reinstall, confirm bot, authorize, reload browser blah blah blah every option available and nothing connecting. Yes Registered and authorized etc. Not a first time user. what is going on guys? Chromebook OS, Mozilla firefox web browser and up to date on all.

Sorry, where did you read that the bot works in mozilla firefox? The bot is only for chromium browsers

**Comment by udo27503** [comment]
And again, its not Working!!
