### ISSUE TITLE
Foe-extender stopped working - Syntax error

### ISSUE THREAD

**Issue by MysteryGrl** [cosmos0nash/FoE-Extender#18]
![Screenshot 2023-12-30 102333](https://github.com/cosmos0nash/FoE-Extender/assets/127634873/1b318d3f-2fde-4801-be90-572e359ba6cd)

I've rebooted, reinstalled, reloaded extension without success. Has something changed or blocking? Is anyone else having same problem or is it only me?

Note: its been working great, only started this problem a few hours ago

**Comment by cosmos0nash** [comment]
Please contact me at https://www.foe-extender.com/contact

**Comment by unknownelement246** [comment]
I cannot even get it to download nor an answer from the creator about the cost :(

**Comment by unknownelement246** [comment]
Does the auto fight battle grounds work well I could care less about the other functions but my finger gets sore fighting lol

**Comment by cosmos0nash** [comment]
> I cannot even get it to download nor an answer from the creator about the cost :(

Everything is on the website, why these questions? Is it difficult to read the help?

**Comment by unknownelement246** [comment]
Everything is on the website, why these questions? Is it difficult to read the help?

obviously it is or I would not be asking  I find the directions totally SUCK
