### ISSUE TITLE
Error in Chrome Version 121.0.6167.161 (Offizieller Build) (64-Bit)

### ISSUE THREAD

**Issue by Snow1234Snow** [cosmos0nash/FoE-Extender#19]
Unfortunately, an error has suddenly occurred since today:

![image](https://github.com/cosmos0nash/FoE-Extender/assets/159476517/da8f23b3-4cb0-4335-882c-7719002a1355)

I have already reinstalled. It still works in other browsers. What can I do?

**Comment by cosmos0nash** [comment]
Clear your browser cache
