### ISSUE TITLE
Can't load Index.js

### ISSUE THREAD

**Issue by noaquie** [cosmos0nash/FoE-Extender#21]
Can't seem to load Index.js.  Says it's looking for in in SCR/Popup/.  No such folder.  Created that folder put the offending file in it then is says can load manifest.  HOW DO I GET THIS TO WORK?

**Comment by cosmos0nash** [comment]
This extension is for Chromium browsers only. Just download the archive, unzip it and select the folder in your browser. All this is described on the main page and in the help.
