### ISSUE TITLE
Sniping.

### ISSUE THREAD

**Issue by Trezorius** [cosmos0nash/FoE-Extender#23]
Good day,
It would be possible to slow down the SNIPING function. It is extremely hard on the server and easily detectable by IMMNO. So add time regulation as it is in BG where it is possible to set the attack repetition time and set something like that in Sniping. For example, the response should be 5 seconds. Well thank you.

**Comment by cosmos0nash** [comment]
This functionality already exists in the bot, option "Delay between GB requests, sec.". Read the help https://foe-extender.com/help#snipe
