### ISSUE TITLE
credit card

### ISSUE THREAD

**Issue by sinanelms** [cosmos0nash/FoE-Extender#6]
I want to buy it, but I can't buy it because we can't use paypal in Turkey, can you create an alternative to purchase via credit card(visa or mastercard)?

**Comment by cosmos0nash** [comment]
> I want to buy it, but I can't buy it because we can't use paypal in Turkey, can you create an alternative to purchase via credit card(visa or mastercard)?
Right now this is not possible, you can only pay through paypal.

**Comment by sinanelms** [comment]
I do not have a paypal account, we cannot open a paypal account in Turkey at the moment, please create another payment tool other than paypal.
