### ISSUE TITLE
popup.html empty

### ISSUE THREAD

**Issue by RiseMe-origami** [cosmos0nash/FoE-Extender#7]
Hi, so I have encountered an issue, where the popup.html is empty hence I cant authorize the bot.
Any advice on how to fix it?

**Comment by cosmos0nash** [comment]
> Hi, so I have encountered an issue, where the popup.html is empty hence I cant authorize the bot. Any advice on how to fix it?

Uninstall the bot extension, clear browser cache, reload the game, install latest version of extension again, authorization menu moved to main window of the bot
