### ISSUE TITLE
Auto BG ist not working (Chrome Browser) 

### ISSUE THREAD

**Issue by tigertim08** [cosmos0nash/FoE-Extender#9]
Hello, I would need some help with the Auto BG. It shows me the right time and province but it just won't attack when the time comes. Any Idea what I missed? 
![2023-07-10_11-11-16](https://github.com/cosmos0nash/FoE-Extender/assets/24661102/4add5ad6-6583-4be5-ad4e-a9893ade381e)
![2023-07-10_11-11-27](https://github.com/cosmos0nash/FoE-Extender/assets/24661102/385e4fbb-956a-4d22-8d8c-5461f9a89018)

**Comment by cosmos0nash** [comment]
> Hello, I would need some help with the Auto BG. It shows me the right time and province but it just won't attack when the time comes. Any Idea what I missed? ![2023-07-10_11-11-16](https://user-images.githubusercontent.com/24661102/252291770-4add5ad6-6583-4be5-ad4e-a9893ade381e.png) ![2023-07-10_11-11-27](https://user-images.githubusercontent.com/24661102/252292167-385e4fbb-956a-4d22-8d8c-5461f9a89018.png)

So maybe its because you enable option "attack acording signals", but there are no signals present

**Comment by tigertim08** [comment]
> > Hello, I would need some help with the Auto BG. It shows me the right time and province but it just won't attack when the time comes. Any Idea what I missed?
> 
> So maybe its because you enable option "attack acording signals", but there are no signals present

Thanks, but i tried both, with signals and without. Both did not work...

**Comment by cosmos0nash** [comment]
> > > Hello, I would need some help with the Auto BG. It shows me the right time and province but it just won't attack when the time comes. Any Idea what I missed?
> > 
> > 
> > So maybe its because you enable option "attack acording signals", but there are no signals present
> 
> Thanks, but i tried both, with signals and without. Both did not work...

Oh, I see that you don't set "Till attacks" option, that's why. You must specify this option

**Comment by tigertim08** [comment]
Thanks! Now it works :)
